sudo: required
services:
  - docker
  
before_install:
  - docker build -t cstockdill/docker-react -f Dockerfile.dev .
  
script:
    - docker run -e CI=true cstockdill/docker-react npm run test -- --coverage